# SatRain Dataset Configuration for Fully Connected Model
base_sensor = "gmi"         # 'gmi' or 'atms'
geometry = "on_swath"       # "gridded" or "on_swath"
subset = "s"               # "xs", "s", "m", "l", "xl"
format = "tabular"

# Retrieval input configurations (all inputs defined here are active by default)
[[retrieval_input]]
name = "gmi"
include_angles = false     # Include earth incidence angles
normalize = "minmax"       # "standardize", "minmax", or null
nan = -1.5                 # Value to replace NaN with   
