accelerator = "cpu"
devices = [0]
precision = "32"
max_epochs = 100
batch_size = 32
approach = "random_forest_training"
num_workers = 8
pin_memory = true
persistent_workers = false
accumulate_grad_batches = 1
log_every_n_steps = 1
check_val_every_n_epoch = 1

[random_forest]
n_estimators = 100
max_depth = "null"
min_samples_split = 2
min_samples_leaf = 1
max_features = "sqrt"
bootstrap = true
random_state = 42
n_jobs = -1